### ISSUE TITLE
Browserify example in documentation does not run.

### ISSUE THREAD

**Issue by jonpacker** [koajs/bundle#6]
Hi!

I'm on `node@4.0.0`, `koa-bundle@^1.0.13` and `koa@^1.0.0`. The first example, the browserify one, in the documentation fails to run. Here is my code:

``` javascript
var koa = require('koa');
var Bundle = require('koa-bundle');
var browserify = require('browserify');

var app = koa()

var bundle = Bundle({debug:true},function(file, fn) {
  browserify({debug:true}).add(file.path).transform(require('babelify')).bundle(fn)
});
app.use(bundle('js/index.js'))

app.listen(3000);
```

Here's what happens when I try to run it:

```
Venjetindan:mobill jonpacker$ node index.js
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at posix.join (path.js:477:5)
    at fullpath (/Users/jonpacker/Development/Projects/mobill/node_modules/koa-bundle/index.js:426:30)
    at entry (/Users/jonpacker/Development/Projects/mobill/node_modules/koa-bundle/index.js:116:12)
    at _bundle (/Users/jonpacker/Development/Projects/mobill/node_modules/koa-bundle/index.js:87:19)
    at Object.<anonymous> (/Users/jonpacker/Development/Projects/mobill/index.js:10:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by matthewmueller** [comment]
interesting, can you try running it again, this time with:

```
DEBUG=koa-bundle* node index.js
```

**Comment by niftylettuce** [comment]
```
> standard-signature@0.0.1 start /Users/nexus/Public/standard-signature
> node lib/

  koa-router defined route  /app(.*) +0ms
  koa-router defined route HEAD,GET /app/ +3ms
  koa-redis Init redis new client +6ms
  koa:application use - +14ms
  koa:application use logger +1ms
  koa:application use - +5ms
  koa-better-static static "/Users/nexus/Public/standard-signature/static-assets" {"maxage":86400000} +1ms
  koa:application use serve +0ms
'TypeError: Path must be a string. Received undefined\n    at assertPath (path.js:8:11)\n    at posix.join (path.js:479:5)\n    at fullpath (/Users/nexus/Public/standard-signature/node_modules/koa-bundle/index.js:429:30)\n    at entry (/Users/nexus/Public/standard-signature/node_modules/koa-bundle/index.js:120:12)\n    at _bundle (/Users/nexus/Public/standard-signature/node_modules/koa-bundle/index.js:88:19)\n    at Object.<anonymous> (/Users/nexus/Public/standard-signature/src/index.js:196:9)\n    at Module._compile (module.js:398:26)\n    at Object.Module._extensions..js (module.js:405:10)\n    at Module.load (module.js:344:32)\n    at Function.Module._load (module.js:301:12)\n    at Function.Module.runMain (module.js:430:10)\n    at startup (node.js:141:18)\n    at node.js:980:3'
```

**Comment by niftylettuce** [comment]
It gets an error before any debugging occurs; I've reproduced this bug.

**Comment by niftylettuce** [comment]
```
root undefined entry editor.js options undefined
root undefined entry editor.js
```

**Comment by niftylettuce** [comment]
It's saying that the root is undefined

**Comment by niftylettuce** [comment]
Okay I'll submit a documentation update, You just have to specify a `root` property in your options along with stuff like `debug: true`

**Comment by niftylettuce** [comment]
Here's how I get scripts to get dynamically loaded:

``` js
let bundle = new Bundle({
  debug: true,
  root: __dirname
}, function(file, fn) {
  Browserify({ debug: file.debug })
    .add(file.path)
    .transform(babelify)
    .bundle(fn);
});

// this is a middleware that makes your scripts
// dir get served up as browserified/babelified
app.use(async function(ctx, next) {

  if (ctx.path.indexOf('/scripts/') !== 0)
    return next();

  let ext = path.extname(path.basename(ctx.path));
  if (ext !== '.js')
    return next();

  try {
    await convert(bundle(ctx.path))(ctx, next);
  } catch (err) {
    ctx.throw(404);
  }

});
```
